# postgresql 特有配置部分
[PostgreSQL]
Username     = "zhangliubin"
Password     = "difyai123456"
DBName       = "copilot_engine_dev"
DBDriver     = "postgres"
Host         = "127.0.0.1"
Port         = 5432
# ConnMaxLifeTime 连接复用最长时间，单位 ms
# 若为0-则不限制，连接不会关闭
# 可以根据线上实际情况，设置一个比较大的合适的时间，以减少创建新连接带来的不稳定性
ConnMaxLifeTime = 300000 # 单位 ms

SQLLogLen      =-1    # 打印sql内容，为0不打印，-1 为全部
SQLArgsLogLen  =-1    # 打印sql参数内容，为0不打印，-1 为全部
LogIDTransport = true # 是否sql注释传递logid

# PostgreSQL 连接参数已直接在代码中设置
# sslmode: disable, require, verify-ca, verify-full
# TimeZone: 时区设置
